#!/bin/bash
man

#!/bin/bash
pwd

#!/bin/bash
ls

#!/bin/bash
cd

#!/bin/bash
cd/

#!/bin/bash
cd..

#!/bin/bash
touch

#!/bin/bash
echo

#!/bin/bash
cat

#!/bin/bash
shred

#!/bin/bash
mkdir

#!/bin/bash
cp

#!/bin/bash
mv

#!/bin/bash
chmod

#!/bin/bash
chown

#!/bin/bash
ifconfig

#!/bin/bash
ping

#!/bin/bash
find

#!/bin/bash
sort

#!/bin/bash
diff

#!/bin/bash
cmp

#!/bin/bash
tail

#!/bin/bash
head

#!/bin/bash
less

#!/bin/bash
unzip

#!/bin/bash
zip

#!/bin/bash
curl

#!/bin/bash
Wget

#!/bin/bash
whatis

#!/bin/bash
finger

#!/bin/bash
sudo apt update

#!/bin/bash
rm

#!/bin/bash
rmdir

#!/bin/bash
clear

#!/bin/bash
whoami

#!/bin/bash
su
